monitor=eDP-1,1920x1080@60,auto,1
monitor=,preferred,auto,auto,mirror,eDP-1
exec-once = regreet; hyprctl dispatch exit

misc {
    disable_hyprland_logo = false
    force_default_wallpaper = 2
    disable_splash_rendering = true
    disable_hyprland_qtutils_check = true
}

animations {
	enabled = false
}

env = AQ_NO_MODIFIERS,1
